In [1]:
# Flask
import flask # 웹서버 기능 5000번 포트로 서비스

In [4]:
import matplotlib # 시각화 패키지
import numpy as np # 별칭 class

print(np.__version__) # 상위 오브젝트가 가진 속성 ( __00__ )

def pprint(arr): # ndarray : numpy의 기본 데이터 배열
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n",arr)
    # 숫자의 디폴트는 int32
    
arr = [1.0,2.0,3.0] # 리스트
a = np.array([1,2,3]) # ndarray 생성함수 (매개변수 : 리스트) => 리스트를 numpy의 ndarray로 만든다. (*초기화할 땐 np를 붙여줘야 함)
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimension:1, dtype:int32
Array's Data:
 [1 2 3]


In [6]:
# 인스턴스 상태

a = np.array([0,1,2,3,4,5,6,7,8,9]) # 리스트 값을 받아서 ndarray를 만든다(a)
print(id(a)) # id() : 주소값 확인
print(a.size) # a의 크기(데이터 개수) : 10개 = 10
print(a.astype(np.float32)) # astype() : 데이터 타입을 변경 => a의 값을 실수형으로 나타냄. numpy는 행중심, 동질적
print(a.dtype.itemsize*a.size) # float32 사이즈 * a.size = 전체 데이터 사이즈(바이트)

# literator   for in range : 리스트를 만듦 / for in arange : ndarray를 만듦
a = np.arange(1000)
a

1707239645632
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [10]:
print(np.zeros((3,4))) # 3행 4열 배열을 0으로 가득 채운다.
print(np.ones((2,3,4),dtype=np.int16)) # 데이터 타입을 지정해서 저장할 수 있다. => 3차원 2면 3행 4열
#ones(2,3,4) : '1'로 2면 3행 4열을 만들어라
print(np.full((2,2),7)) # 2행 2열을 7로 가득한 행렬을 만들어라
print(np.eye(4)) # 대각행렬 identity
print(np.empty((4,2))) # 4행 2열 행렬을 쓰레기 값으로 채워라

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.00783825e-321]
 [3.11521375e-307 1.89144859e-307]]


In [12]:
a = np.arange(0, 100, 10) # 0부터 99까지 10단위로 끊어서 범위 지정 : ndarrat

indices = [1,5,-1] # 리스트
print(indices)

b = a[indices] # 리스트를 첨자로 함.
print(a)
print(b) # a.indices = a.[1], a.[5], a[-1] = 10, 50, 90(뒤에서 첫번째 : -1)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [14]:
a = np.arange(11,36) # 1차원으로 생성

a.shape = (5,5) # 5행 5열로 보여줘라 *개수가 맞아야 함.
print(a)

print(type(a)) #<class 'numpy.ndarray'>
print(a.dtype)
print(a.size) 25개
print(a.shape) # 차수 (5,5)
print(a.ndim) # 2차원
print(a.nbytes) # *바이트 * 25개 = 100
print(a.strides) # (20,4) : 다음 열의 데이터는 몇 바이트를 건너뛰어야 하는가
                # 다음 행은 몇 바이트를 건너뛰어야 하는가. 한 행이 5열로 이루어져 있는데, 한 데이터마다 4바이트니까......

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [16]:
arr = np.arange(10) # 0 ~ 9

print(type(arr))

print(arr)
print(arr[5])
print(arr[5:8]) # 마지막은 불포함 => arr[5],arr[6],arr[7] 출력
arr[5:8]=12 # 5,6,7 = 12로 데이터 업데이트
print(arr[1:6])

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [19]:
# numpy 첨자 생략 불가 : ex) [,4]

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2d[0]) # 행 우선 : 행
print(arr2d[0][2])
print(arr2d[0,2])
print(arr2d[:2]) # 0,1 행 출력
print(arr2d[:2,1:]) # 0,1 행, 1행부터 끝까지 출력
print(arr2d[:,1:]) # 모든 행
print(arr2d[1,:2]) # 1행 2열까지만 출력
print(arr2d[2, :1])
arr2d[:2,:1]=0
arr2d[:2,:1]=0
print(arr2d)

[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]
 [8 9]]
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [20]:
# 실제 저장은 일렬로, 사람이 데이터를 다루는 것은 입체로.
# 행렬연산에서 앞의 행렬열수와 뒤의 행렬의 행수를 일치 시켜야 행렬곱이 가능
# 행렬곱에서 행렬 앞뒤로 바꾸면 안됨

print("스트라이드의 값", np.ones((3,4,5), dtype=np.float64).strides)

스트라이드의 값 (160, 40, 8)


In [ ]:
# 단일 데이터 float 64 : 8바이트
# 다음 데이터로 가려면 "8"바이트를 지나야 하고, 다음 행으로 가려면 5개*8바이트 = 40 바이트를 지나야 하고,
# 다음 면으로 가려면 나머지 4행을 지나야 하니까 4행 * 40바이트(한 행) = 160 바이트

In [35]:
# 문제
arr3d = np.array([[[1,2,3],[4,5,6]],  [[7,8,9],[10,11,12]]]) # 면이 2개, 행이 2개, 열이 3개 => 2,2,3
print("첫 차원", arr3d[0])
print("첫 차원 첫 행은 = ", arr3d[0][0])
print("첫 요소는 = ", arr3d[0][0][0])


# 8을 출력하시오
print(arr3d[1][0][1])
# 12 출력
print(arr3d[1][1][2])

print(arr3d)

첫 차원 [[1 2 3]
 [4 5 6]]
첫 차원 첫 행은 =  [1 2 3]
첫 요소는 =  1
8
12
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [36]:
# old_values=arr3d <-로 돌리면 백업이 안됨 : 입하면 같은 주소를 가리키기 때문.  # 대입 : 주소를 복사
old_values=arr3d.copy()

arr3d[0]=42

print("값의 변경 후")
print(arr3d)

print("값 이전으로 복구")
arr3d = old_values

print(arr3d)

값의 변경 후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
값 이전으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [40]:
Z = np.arange(36) # 1차원 리스트
Z = Z.reshape((6,6)) # Z의 값을 6행6열로 바꾸어라
print(Z)

print()

reshape2 = Z.reshape((2,3,6)) # 6행 6열을 2면 3행 6열로 바꾸어라
print(reshape2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [42]:
arr=np.arange(32).reshape((8,4))
print(arr)
print()
print(arr[[1,5,7,2]]) # 행중심
print()
print(arr[[-1,-5,-7,-2]]) # 거꾸로 인덱싱
print()
print(arr[[1,6,7,2],[0,3,1,2]])
print()
# fancy 인덱싱
print(arr[[1,2,5,7]][:,[0,1,2,3]]) # 1,2,5,7행을 출력하고, 앞에 나온 행(1,2,5,7행)의 0,1,2,3,열을 출력하라.
print()
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]

[ 4 27 29 10]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [48]:
arr = []
for i in range(6):
    ad = []
    for j in range(6):
        ad.append(i*10 + j)
    arr.append(ad)
#print(arr)
arr = np.array(arr)

print(arr)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
주황색 [ 1 12 23 34 45]


In [54]:
print("주황색", arr[[0,1,2,3,4],[1,2,3,4,5]])
print("빨강색", arr[[0,2,5],2])
print("하늘색", arr[3:6][:,[0,2,5]])

주황색 [ 1 12 23 34 45]
빨강색 [ 2 22 52]
하늘색 [[30 32 35]
 [40 42 45]
 [50 52 55]]


In [69]:
print("빨강색", arr[0:6][:,2])
print("주황색", arr[[0],[2,3,4]])
print("연두색", arr[[2,4]][:,[0,2,4]])
print("하늘색", arr[3:6][:,[0,2,5]])
print("green = ", arr[4:][:,[4,5]])

빨강색 [ 2 12 22 32 42 52]
주황색 [2 3 4]
연두색 [[20 22 24]
 [40 42 44]]
하늘색 [[30 32 35]
 [40 42 45]
 [50 52 55]]
green =  [[44 45]
 [54 55]]


In [77]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # 4행 3열 ndarray
v = np.array([1,0,1])

print("x = ",x)
print("v = ",v)
print()

print("단일 출력")

vv = np.tile(v, (4,1)) # v의 내용으로 4행 1열을 만들어라
print(vv)
print()

y = x + vv # x 배열 + vv 배열 => 행렬 생성 (요소별로 연산)
print(y)
print()

print(x+v) # 4*3, 1*3 broadcasting : 차수가 맞지 않을 땐 적은 곳을 자동으로 *n 함 (양쪽 차원이 같아야 하기 때문)
x+3

x =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
v =  [1 0 1]

단일 출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [82]:
x = np.arange(6).reshape((3,2))
print(x)
# 거듭제곱 (행열곱)
# 앞의 행렬의 열수와 뒤의 행렬의 행수가 일치해야 함 => 3*2, 2*3 => " 함수 .T "
x@x.T 
print(np.transpose())

[[0 1]
 [2 3]
 [4 5]]


array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [90]:
arr = np.arange(24).reshape((2,3,4)) # 2면 3행 4열

print(arr)
print("-------------")

print(arr.transpose((1,0,2))) #  1,0 <- 면과 행을 바꾸어라. => 3면 2행 4열
print()

print("-----")

print(arr.transpose((0,2,1))) # 면,행,열을 바꿔라 => 2면 4행 3열

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
-------------
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

-----
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [97]:
# Boolean indexing
# 문자열은 대소문자 구분
names = np.array(['Seoul','Daejun','chungju','seoul','chungju','Daejun','Daejun'])
data = np.random.randn(7,4) # 7행 4열로 된 데이터

print(names)
print()

print(names=='Seoul') # 1,0,0,0,0,0,0
print()
print(data[names=='Seoul']) # 0번 행만 출력하라
print()
print(data[names=='Seoul',2:])
print()
print(data[names=='Seoul',3])
print()
print(names != 'Seoul')
print()
print(~(names == 'Seoul'))
print()
mask = (names == 'Seoul') | (names == 'chungju')
print()
print(mask)
print()
print(data[mask])

['Seoul' 'Daejun' 'chungju' 'seoul' 'chungju' 'Daejun' 'Daejun']

[ True False False False False False False]

[[ 0.60765531  0.13406802 -1.64813687  0.54411585]]

[[-1.64813687  0.54411585]]

[0.54411585]

[False  True  True  True  True  True  True]

[False  True  True  True  True  True  True]


[ True False  True False  True False False]

[[ 0.60765531  0.13406802 -1.64813687  0.54411585]
 [ 0.13652804 -0.90237448 -2.47375899  0.02420508]
 [ 0.31004918 -1.70108836 -2.13085387  2.37459984]]


In [104]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

print(zip(xarr,yarr, cond)) # zip() : 요소별로 데이터를 묶을 때 사용 (열 중심)
#  - zip은 바로 print 안됨 -> list로 만들고 출력

result = [(x if c else y ) for x,y,c in zip(xarr,yarr,cond)] # 3항 연산자
# c일 때 참이면 x 출력, 거짓이면 y 출력 -> 1.1, 2.2, 1.3, 1.4, 2.5
print("result = ", result)

print()
arr = np.random.randn(4,4) # 랜덤으로 4행 4열 만들기
print(arr)

print(np.where(arr>0, 2, -2))
#arr이 0보다 크면 2, 0보다 작으면 -2 출력

result =  [1.1, 2.2, 1.3, 1.4, 2.5]

[[ 0.56602885 -1.83800221 -1.08056673  0.84368285]
 [-1.05200013  0.40470571 -1.25299851  0.94024917]
 [-0.7057451   1.76394675  0.79437289  1.15083436]
 [ 0.43626303  0.5671403  -0.61187088 -1.48651181]]
[[ 2 -2 -2  2]
 [-2  2 -2  2]
 [-2  2  2  2]
 [ 2  2 -2 -2]]


In [113]:
# 문제) 다음 데이터를 이용하여 두 개 다 참일 때는 0, cond1이 참일 때는 1, cond2가 참일 때는 2, 그 외에는 3으로 처리하여 출력해라.
# 0,1,2,3
# 조건 4
# where 3항 연산자


result = []
cond1 = np.array([1,0,1,1,0,0,1],dtype=bool )
cond2 = np.array([0,1,1,1,0,1,1],dtype=bool )

print(cond1)
print(cond2)

for i in range(len(cond1)):
    if(cond1[i] and cond2[i]):
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
print("조건문", result)

result = np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2, 2, 3)))
print("3항 연산자", result)

result = 1*(cond1 & ~cond2) + 2*(cond2& ~cond1) + 3* ~(cond1 | cond2)
print("수식을 이용한", result)

[ True False  True  True False False  True]
[False  True  True  True False  True  True]
조건문 [1, 2, 0, 0, 3, 2, 0]
3항 연산자 [1 2 0 0 3 2 0]
수식을 이용한 [1 2 0 0 3 2 0]


In [115]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

z = np.zeros_like(x) # 다른 행렬(x)과 같은 사이즈로 (z를) 초기화

for i in range(10000):
    z[i] = x[i] + y[i]
    
print(z)


[10002 10004 10006 ... 29996 29998 30000]


In [118]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

print(np.all(a==b)) # 전체가 참일 때 참
print(np.any(a==b)) # 하나라도 참이면 참
print(np.exp(a))    # 지수함수 (자연대수 : 2.718)

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
# 선형대수 : 모든 문제를 선형으로 해결하자. => 비선형도 잘게 나누면 선형(미분)
# 선형대수의 가장 기본적인 건, 

### 행렬의 종류
- 정방행렬 : 정사각형 (행의 수 = 열의 수)
- 대칭행렬 : 우상단과 좌하단이 같은 것
- 대각행렬 : scale을 변화시키는 요소
- 단위행렬(identity) : 행렬곱의 항등원
- 역행렬 : 행렬의 나눗셈을 위해 구해서 곱해지는 행렬
- 특이행렬 : 역행렬이 없는 행렬
- 직교행렬 : 축의 정직교, 각 축간의 내적이 0인 행렬
- 정방행렬이면서 대칭행렬인 것 = 공분산행렬, 상관계수행렬
- 공분산 : 두 수 간의 관계 -> ((한 수 - 평균) * (다른 수 - 평균))/(n-1)
- 상관계수(표준화 -1 ~ 1) : 공분산 / 표준편차의 곱


In [120]:
import numpy as np
F1 = np.array([[1,2],[3,4]])
F2 = np.array([[2,2],[2,2]])

print(F1)
print()

print(F2)
print()

print(F1 + F2)
print()

print(F1 * F2)
print()

print(F1 @ F2) # 행렬곱도 내적

[[1 2]
 [3 4]]

[[2 2]
 [2 2]]

[[3 4]
 [5 6]]

[[2 4]
 [6 8]]

[[ 6  6]
 [14 14]]


## 방정식의 해
### 2 x 1 +  x2       2x3 = -3
### 3 x 1 +            x3 = 5
###   x 1 + x2         x3 = -2

이게 대체 뭔 소리당가..

In [128]:
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(A)
print()

b=np.transpose(np.array([[-3,5,-2]])) # 열로 전치
print(b)
print()

x = np.linalg.solve(A,b) # A의 역행렬을 구해서 b와 곱 해줌
print(x)
print()

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]

[[-3]
 [ 5]
 [-2]]

[[ 1.]
 [-1.]
 [ 2.]]



In [130]:
np.dot(np.linalg.inv(A),b) # 행렬곱

array([[ 1.],
       [-1.],
       [ 2.]])

In [131]:
np.linalg.inv(A)@b # 왜 역행렬을 구해야 하는가? => 행렬은 나눗셈이 없어서 역행렬을 곱해서 나눈다.

array([[ 1.],
       [-1.],
       [ 2.]])

In [132]:
# 검산
2*1 + (-1)  -2*2

-3

In [134]:
a = np.array([0,1,0]) # X축
b = np.array([1,0,0]) # Y축
res = np.dot(a,b) # 내적 사이각 : 내적이 0이면 직각
print(res)

0


In [136]:
print(np.linalg.norm(a)) # 벡터의 크기
print(np.linalg.norm(b))
print(np.linalg.norm(a) * np.linalg.norm(b))
rad = res / (np.linalg.norm(a) * np.linalg.norm(b)) # cos(theta)
print("cos theta", rad)
print(np.arccos(rad)) # theta 값을 구함
print(np.degrees(np.arccos(rad))) # 사람이 알아보는 각도로 표현

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [137]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


### 다음 방정식의 해를 구하고 검산하시오
- x + y + z = 6
- 2y + 5z = -4
- 2x + 5y -z = 27

In [145]:
first = np.array([[1,1,1],[0,2,5],[2,5,-1]])
second = np.transpose(np.array([[6,-4,27]]))

print(first)
print()
print(second)
print()

output = np.linalg.solve(first,second)
print(output)

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]

[[ 6]
 [-4]
 [27]]

[[ 5.]
 [ 3.]
 [-2.]]


In [149]:
# 검산
print(5+3-2)
print(2*3 + 5*(-2))
print(2*5 + 5*3 + (-1)*(-2))

6
-4
27
